# Generated by Django 4.2.7 on 2023-11-02 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='war.tipo'),
        ),
    ]
