# Generated by Django 4.2.7 on 2023-11-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0003_habilidade_borda_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidade',
            name='borda_cor',
        ),
    ]
