# Generated by Django 4.2.7 on 2023-11-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0004_remove_habilidade_borda_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
